[package]
name = "crow_engine"
version = "0.1.0"
edition = "2024"

[dependencies]
jni = "0.21.1"
libloading = "0.9.0"
flate2 = "1.1.9"
lazy_static = "1.4"
winapi = "0.3.9"

[lib]
crate-type = ["cdylib"]